apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/ingress.yaml
- base/serviceaccount-admin.yaml
- https://raw.githubusercontent.com/kubernetes/dashboard/v2.6.0/aio/deploy/recommended.yaml


namespace: kubernetes-dashboard
patches:
- path: base/dashboard-metric-scraper-deployment-patch.yaml
  target:
    kind: Deployment
- path: base/kubernetes-dashboard-deployment-patch.yaml
  target:
    kind: Deployment
